### PR TITLE
Complete beam def

### PR DESCRIPTION
**Pull request by delph74**
It was not possible (or at least I didn't find how) to add a beam to a sequence. Now it follows the same pattern as adding initial conditions to a range.

### CODE REVIEW

**Comment by kaifox** [comment]
Hi Delphine, very good initiative!
First comment: Could you probably check why the checks fail (travis build) and potentially fix them?

**Comment by kaifox** [comment]
Was this the only change? Renaming OngoingBeam to BeamBlock and use a consumer? Or is thi pull request missing some files?

**Comment by kaifox** [comment]
Indeed .. .very good! It seems that there was unfifished stuff with the beam ;-)

Alternatively, to avoid a bit of even  more nesting, one could have kept the OngoingBeam concept... the methods then just would have to be completed with `return this;` .. and beams could have been written as 
`
s.beam().particle(PROTON); ... I think this was the original idea but the returns where missing ;-)
`

**Comment by delph74** [comment]
Indeed I hesitated between the 2 solutions, then I decided it was better to have it defined in a similar way than InitialConditions. To avoid confusion, we could change none or both I think.

**Pull request merged**
